import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const GTWalsheimPro = localFont({
  src: [
    // {
    //   path: "../public/GTWalsheimPro-UltraLight.ttf",
    //   weight: "200",
    //   style: "normal",
    // },
    // {
    //   path: "../public/GTWalsheimPro-Light.ttf",
    //   weight: "300",
    //   style: "normal",
    // },
    // {
    //   path: "../public/GTWalsheimPro-Thin.ttf",
    //   weight: "400",
    //   style: "normal",
    // },
    {
      path: "../public/GTWalsheimPro-Regular.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/GTWalsheimPro-Medium.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/GTWalsheimPro-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/GTWalsheimPro-UltraBold.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-gtwalsheim",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GTWalsheimPro.className}>{children}</body>
    </html>
  );
}
